// ==========================================
// app/lib/pgAdapter.js
// Adapter PostgreSQL (async, pool) dengan antarmuka execute({sql,args}) supaya
// kode web yang memakai `db.execute({ sql, args })` + `res.rows` /
// `res.rowsAffected` / `res.lastInsertRowid` TIDAK perlu diubah.
//
// KENAPA: migrasi dari engine lama ke PostgreSQL (Supabase). Alih-alih menulis
// ulang 223 pemanggilan .execute(), kita ganti engine-nya di satu tempat ini.
//
// PEMETAAN:
//   - placeholder `?` -> `$1,$2,...` (gaya SQLite -> gaya Postgres).
//   - execute(sql) / execute({sql,args}) -> { rows, rowsAffected, lastInsertRowid }
//   - executeMultiple(sql) -> menjalankan banyak statement (DDL skema).
//   - INSERT OR IGNORE/REPLACE -> ON CONFLICT (via translator bersama).
// ==========================================

import pg from 'pg';

const { Pool } = pg;
let _pool = null;

function getPool() {
  if (_pool) return _pool;
  const url = process.env.DATABASE_URL || process.env.PG_URL;
  // Tabel web ada di schema 'web' (terpisah dari tabel bot di 'public') supaya
  // nama tabel yang sama (mis. `users`) tidak bentrok. search_path mengarahkan
  // query tanpa prefix ke schema web.
  const schemaOpt = process.env.PG_SCHEMA ? `-c search_path=${process.env.PG_SCHEMA},public` : '-c search_path=web,public';
  if (url) {
    _pool = new Pool({
      connectionString: url,
      ssl: /supabase|neon|sslmode=require/i.test(url) ? { rejectUnauthorized: false } : undefined,
      max: 5,
      options: schemaOpt,
    });
  } else {
    _pool = new Pool({
      host: process.env.PGHOST || 'localhost',
      port: parseInt(process.env.PGPORT || '5432', 10),
      user: process.env.PGUSER || 'postgres',
      password: process.env.PGPASSWORD || undefined,
      database: process.env.PGDATABASE || 'nexo',
      max: 5,
      options: schemaOpt,
    });
  }
  return _pool;
}

// `?` -> `$1,$2,...` (sadar string literal sederhana).
function toPgPlaceholders(sql) {
  let i = 0;
  let out = '';
  let inStr = false;
  for (let k = 0; k < sql.length; k++) {
    const c = sql[k];
    if (c === "'") { inStr = !inStr; out += c; continue; }
    if (!inStr && c === '?') { out += '$' + (++i); continue; }
    out += c;
  }
  return out;
}

// Terjemah dialek SQLite -> PG (INSERT OR IGNORE/REPLACE, excluded, unixepoch).
function translate(sql) {
  let s = sql;
  if (/\bINSERT\s+OR\s+IGNORE\s+INTO\b/i.test(s) && !/\bON\s+CONFLICT\b/i.test(s)) {
    s = s.replace(/\bINSERT\s+OR\s+IGNORE\s+INTO\b/gi, 'INSERT INTO').replace(/;\s*$/, '') + ' ON CONFLICT DO NOTHING';
  }
  s = s.replace(/\bexcluded\./g, 'EXCLUDED.');
  s = s.replace(/\bunixepoch\s*\(\s*\)/gi, 'EXTRACT(EPOCH FROM NOW())::bigint');
  s = s.replace(/\bdatetime\s*\(\s*'now'\s*\)/gi, 'NOW()');
  return toPgPlaceholders(s);
}

// Konversi DDL SQLite -> PG (dipakai execute & executeMultiple).
function convertDdl(sql) {
  return sql
    .replace(/\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi, 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
    .replace(/\bAUTOINCREMENT\b/gi, '')
    .replace(/\bINTEGER\b/gi, 'BIGINT')
    .replace(/\bREAL\b/gi, 'DOUBLE PRECISION')
    .replace(/\bunixepoch\s*\(\s*\)/gi, 'EXTRACT(EPOCH FROM NOW())::bigint')
    .replace(/\bdatetime\s*\(\s*'now'\s*\)/gi, 'NOW()');
}

async function _exec(sql, args) {
  // DDL (CREATE/ALTER) juga butuh konversi dialek walau lewat execute().
  const isDdl = /\b(CREATE|ALTER)\s+TABLE\b/i.test(sql);
  const pgSql = isDdl ? convertDdl(sql) : translate(sql);
  const res = await getPool().query(pgSql, args || []);
  return {
    rows: res.rows,
    rowsAffected: res.rowCount,
    lastInsertRowid: res.rows && res.rows[0] && res.rows[0].id !== undefined ? res.rows[0].id : undefined,
  };
}

function createPgClient() {
  return {
    // Dua bentuk didukung (gaya lama + gaya ringkas):
    //   execute('SELECT ...', [args])        <- dipakai lib/snapshot.js
    //   execute({ sql: 'SELECT ...', args }) <- dipakai halaman lain
    async execute(stmt, args2) {
      if (typeof stmt === 'string') return _exec(stmt, args2 || []);
      if (stmt && typeof stmt === 'object') return _exec(stmt.sql, stmt.args);
      throw new Error('execute: bentuk statement tidak dikenal');
    },
    async executeMultiple(sql) {
      // DDL banyak statement (skema). Konversi dialek SQLite -> PG dulu.
      await getPool().query(convertDdl(sql));
      return { rows: [], rowsAffected: 0 };
    },
    async batch(stmts) {
      const out = [];
      for (const s of stmts) out.push(await this.execute(s));
      return out;
    },
  };
}

export { createPgClient, getPool };
